### ISSUE TITLE
criar models para migrations

### ISSUE THREAD

**Issue by fdemarque** [Seven-Howls/delivery-control-backend#7]
- [x] Model empresa
- [x] Model usuário
- [x] Model permissões
- [x] Model permissões tipo usuário
- [x] Model tipos usuário
- [x] Model colaboradores
- [x] Model métodos de pagamento
- [x] Model status
- [x] Model entregas
- [x] Model taxas entregas
- [x] Model motoboy

**Comment by JoaoVitorMirandaBandeira** [comment]
finish
